# Generated by Django 6.0.3 on 2026-03-18 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitio', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='medicamento',
            options={'ordering': ['-created'], 'verbose_name': 'Medicamento', 'verbose_name_plural': 'Medicamentos'},
        ),
        migrations.AlterField(
            model_name='medicamento',
            name='nombre',
            field=models.CharField(max_length=55),
        ),
        migrations.AlterField(
            model_name='medicamento',
            name='via',
            field=models.CharField(max_length=40),
        ),
    ]
