# Generated by Django 6.0.3 on 2026-03-18 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitio', '0002_alter_medicamento_options_alter_medicamento_nombre_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='libro',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=100)),
                ('autor', models.CharField(max_length=77)),
                ('isbn', models.IntegerField(max_length=13)),
                ('fecha', models.DateField(verbose_name='Fecha de publicación')),
                ('categoria', models.CharField(choices=[('Anatomia', 'Anatomia'), ('Cardiologia', 'Cardiologia'), ('Enfermeria', 'Enfermeria'), ('Farmacologia', 'Farmacologia'), ('Fisiologia', 'Fisiologia')])),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Libro',
                'verbose_name_plural': 'Libros',
                'ordering': ['-created'],
            },
        ),
    ]
