# Generated by Django 6.0.3 on 2026-03-26 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitio', '0003_libro'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='medicamento',
            options={'ordering': ['nombre'], 'verbose_name': 'Medicamento', 'verbose_name_plural': 'Medicamentos'},
        ),
        migrations.AddField(
            model_name='medicamento',
            name='riesgo',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('X', 'X')], null=True, verbose_name='Riesgo en el embarazo'),
        ),
        migrations.AlterField(
            model_name='medicamento',
            name='caption',
            field=models.TextField(verbose_name='Efectos Adversos'),
        ),
    ]
