# Generated by Django 6.0.3 on 2026-03-26 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitio', '0004_alter_medicamento_options_medicamento_riesgo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicamento',
            name='riesgo',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('X', 'X'), ('Desconocido', 'Desconocido')], null=True, verbose_name='Riesgo en el embarazo'),
        ),
    ]
