# Generated by Django 6.0.1 on 2026-04-14 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitio', '0007_nota'),
    ]

    operations = [
        migrations.AddField(
            model_name='nota',
            name='contenido',
            field=models.TextField(default=''),
        ),
    ]
