# Generated by Django 6.0.1 on 2026-04-14 02:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sitio', '0008_nota_contenido'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='nota',
            options={'ordering': ['created'], 'verbose_name': 'Nota', 'verbose_name_plural': 'Notas'},
        ),
    ]
