# Generated by Django 6.0.1 on 2026-04-14 03:10

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sitio', '0009_alter_nota_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nota',
            name='contenido',
            field=ckeditor.fields.RichTextField(default=''),
        ),
    ]
