# Generated by Django 6.0.1 on 2026-04-16 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitio', '0012_usuario_rol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='imagenPerfil',
            field=models.ImageField(blank=True, default='defaults/user.png', null=True, upload_to='imagenes/'),
        ),
    ]
