# Generated by Django 6.0.1 on 2026-04-16 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitio', '0015_alter_usuario_imagenperfil'),
    ]

    operations = [
        migrations.AddField(
            model_name='libro',
            name='url',
            field=models.FileField(blank=True, null=True, upload_to='libros'),
        ),
    ]
