# Generated by Django 6.0.1 on 2026-04-16 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitio', '0017_libro_portada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libro',
            name='url',
            field=models.FileField(blank=True, null=True, upload_to='libros/'),
        ),
    ]
