# Generated by Django 6.0.1 on 2026-04-16 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitio', '0020_alter_libro_portada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libro',
            name='isbn',
            field=models.CharField(max_length=13),
        ),
        migrations.AlterField(
            model_name='libro',
            name='portada',
            field=models.ImageField(blank=True, null=True, upload_to='portadas/'),
        ),
    ]
