# Generated by Django 6.0.1 on 2026-04-16 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitio', '0021_alter_libro_isbn_alter_libro_portada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libro',
            name='categoria',
            field=models.CharField(choices=[('NA', 'NA'), ('Anatomia', 'Anatomia'), ('Cardiologia', 'Cardiologia'), ('Enfermeria', 'Enfermeria'), ('Farmacologia', 'Farmacologia'), ('Fisiologia', 'Fisiologia')]),
        ),
    ]
