# Generated by Django 6.0.1 on 2026-04-16 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitio', '0022_alter_libro_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='libro',
            name='aprobado',
            field=models.BooleanField(default=True),
        ),
    ]
