# Generated by Django 6.0.1 on 2026-04-17 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitio', '0023_libro_aprobado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libro',
            name='isbn',
            field=models.CharField(default='NA', max_length=13),
        ),
    ]
