# Generated by Django 6.0.1 on 2026-04-17 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitio', '0024_alter_libro_isbn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libro',
            name='aprobado',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='libro',
            name='autor',
            field=models.CharField(blank=True, max_length=77, null=True),
        ),
        migrations.AlterField(
            model_name='libro',
            name='fecha',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de publicación'),
        ),
    ]
