# Generated by Django 6.0.1 on 2026-04-17 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitio', '0025_alter_libro_aprobado_alter_libro_autor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libro',
            name='isbn',
            field=models.CharField(blank=True, default='NA', max_length=13, null=True),
        ),
    ]
